"use strict";
exports.__esModule = true;
var Animal_1 = require("./Animal");
var Cat_1 = require("./Cat");
var Dog_1 = require("./Dog");
var animal1 = new Animal_1["default"]("Planet Earth");
console.log(animal1);
console.log("------------------------");
var dog = new Dog_1["default"]("Cozy Home", "Yorkshire Terrier", "Woof Woof");
console.log(dog);
console.log(dog.show());
console.log(dog.talk());
console.log("------------------------");
var cat = new Cat_1["default"]("Another Cozy Home", "Persian", "Meow Meow", "Kitty Kat");
console.log(cat);
console.log(cat.show());
console.log(cat.talk());
console.log("------------------------");
console.log(animal1.show());
